name: Check for broken links on site

on:
  workflow_run:
    workflows: [Deploy site]
    types: [completed]

jobs:
  check-links-on-site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Link Checker (live site)
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: >-
            --verbose
            --no-progress
            --max-redirects 5
            --exclude-mail
            --exclude '^https://fonts\.googleapis\.com/?$'
            --exclude '^https://fonts\.gstatic\.com/?$'
            https://YannisTevissen.github.io/
